ParkingMgmt/Models/BookingSlotViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ParkingMgmt.Models
{
    public class BookingSlotViewModel
    {
        public int Id { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<System.DateTime> AllocatedDate { get; set; }
        public Nullable<System.TimeSpan> AllocatedTime { get; set; }
        public string VehicleType { get; set; }

        
    }
}

ParkingMgmt/Controllers/BookingSlotsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ParkingSlotDataLib;
using ParkingMgmt.Models;

namespace ParkingMgmt.Controllers
{
    public class BookingSlotsController : Controller
    {
        private ParkingSlotEntities db = new ParkingSlotEntities();
        private History his= new History();
  


        public ActionResult HomePage()
        {
            return View();
        }

        public ActionResult AllSlots()
        { 
            return View(db.BookingSlots.ToList());
        }



        public ActionResult ParkingHistory()
        {

            return View(db.History.OrderByDescending(x=>x.AllocatedDate).ToList());
        }

        [HttpGet]
        public ActionResult SlotAvaiabilty()
        {
            // ParkingSlotEntities db = new ParkingSlotEntities();
            ViewBag.DropDown = db.BookingSlots.Select(u => u.VehicleType).Distinct().ToList();
            ViewBag.error = TempData["temp"];
            return View();
        }

        [HttpGet]
        public ActionResult availableslots()  {

            string VT = Request.QueryString["VehicleType"];
            if (VT =="" || VT==null)
            {
                //ViewBag.error = "Please select Vehicle Type";

                TempData["temp"] = "Please select Vehicle Type";
                TempData.Keep();
                return RedirectToAction("SlotAvaiabilty");
            }
            else if (VT == "Large")
            {
                var count = db.BookingSlots.Where(x => x.VehicleType == VT && x.VehicleNumber == null).ToList().Count();
                if (count == 0)
                {
                    ViewBag.error = "Parking Slots Not Avilable";
                }
                else
                {
                    return View(db.BookingSlots.Where(x => x.VehicleType == VT && x.VehicleNumber == null).ToList());
                }
             
            }
            else if(VT=="Medium")
            {
                var count = db.BookingSlots.Where(x => x.VehicleType == VT || x.VehicleType == "Large" && x.VehicleNumber == null).ToList().Count();
                if(count==0)
                {
                    ViewBag.error = "Parking Slots Not Avilable";
                }
                else
                {
                    return View(db.BookingSlots.Where(x => x.VehicleType == VT || x.VehicleType == "Large" && x.VehicleNumber == null).ToList());
                }
                
            }
            else if(VT == "Small")
            {
                var count = db.BookingSlots.Where(x => x.VehicleNumber == null).ToList().Count();
                if(count==0)
                {
                    ViewBag.error = "Parking Slots Not Avilable";
                }
                else
                {
                    return View(db.BookingSlots.Where(x => x.VehicleNumber == null).ToList());
                }
                
            }
            else
            {
                ViewBag.DropDown = db.BookingSlots.Select(u => u.VehicleType).Distinct().ToList();
                return View();
            }

            return View();
         
        }
        public ActionResult BookSlot()
        {
            ViewBag.DropDown = db.BookingSlots.Select(u => u.VehicleType).Distinct().ToList();
            return View();
        }
        [HttpPost]
        public ActionResult BookSlot([Bind(Include = "VehicleNumber,AllocatedDate,AllocatedTime,VehicleType")] BookingSlot bs)
        {
            if(bs.VehicleType!=null&&bs.VehicleNumber!=null)
            {

                if (bs.VehicleType == "Large")
                {

                    var count = db.BookingSlots.Where(x => x.VehicleType == "Large" && x.VehicleNumber == null).ToList().Count();
                    if (count != 0)
                    {
                        var EditedObj = db
                              .BookingSlots
                              .Where(x => x.VehicleType == "Large" && x.VehicleNumber == null)
                              .First();

                        EditedObj.VehicleNumber = bs.VehicleNumber;
                        EditedObj.AllocatedDate = DateTime.Now;
                        EditedObj.AllocatedTime = DateTime.Now.TimeOfDay;
                        db.SaveChanges();
                    }
                }
                else if (bs.VehicleType == "Medium")
                {
                    var EditedObj = db
                             .BookingSlots
                             .Where(x => x.VehicleType == "Medium" || x.VehicleType == "Medium" && x.VehicleNumber == null)
                             .First();
                    EditedObj.VehicleNumber = bs.VehicleNumber;
                    EditedObj.AllocatedDate = DateTime.Now;
                    EditedObj.AllocatedTime = DateTime.Now.TimeOfDay;
                    db.SaveChanges();
                }
                else if (bs.VehicleType == "Small")
                {
                    var EditedObj = db
                             .BookingSlots
                             .Where(x => x.VehicleNumber == null)
                             .First();
                    EditedObj.VehicleNumber = bs.VehicleNumber;
                    EditedObj.AllocatedDate = DateTime.Now;
                    EditedObj.AllocatedTime = DateTime.Now.TimeOfDay;
                    db.SaveChanges();
                }

            }
            else
            {
                ViewBag.DropDown = db.BookingSlots.Select(u => u.VehicleType).Distinct().ToList();
                return View();
            }
            return RedirectToAction("HomePage");
        }

   
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookingSlot bookingSlot = db.BookingSlots.Find(id);
            if (bookingSlot == null)
            {
                return HttpNotFound();
            }
            return View(bookingSlot);
        }

        public ActionResult UnallocateParkingSlot()
        {
            return View(db.BookingSlots.Where(x => x.VehicleNumber != null).ToList());
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookingSlot bookingSlot = db.BookingSlots.Find(id);
            if (bookingSlot == null)
            {
                return HttpNotFound();
            }
            return View(bookingSlot);
        }

        // POST: BookingSlots/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BookingSlot bookingSlot = db.BookingSlots.Find(id);
            his.AllocatedDate = bookingSlot.AllocatedDate.Value;
            his.AllocatedTime = bookingSlot.AllocatedTime.Value;
            his.VehicleNo = bookingSlot.VehicleNumber;
            his.SlotNo = bookingSlot.SlotNo.Value;
            his.UnAllocatedDate = DateTime.Now;
            his.UnAllocatedTime = DateTime.Now.TimeOfDay;
            bookingSlot.VehicleNumber = null;
            bookingSlot.AllocatedDate = null;
            bookingSlot.AllocatedTime = null;
            db.History.Add(his);
            db.SaveChanges();
            return RedirectToAction("UnallocateParkingSlot");

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ParkingMgmt/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ParkingMgmt.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

    }
}

ParkingMgmt/Views/BookingSlots/AllSlots.cshtml
@model IEnumerable<ParkingSlotDataLib.BookingSlot>


<h2>Avialable Slots</h2>

<style>
    body {
        margin: 4rem 0;
    }

    h4 {
        margin-bottom: 2rem;
        margin-top: 3rem;
    }

    .panel {
        height: auto;
        width: auto;
        border-radius: 0.2rem;
        padding: 0.5rem;
        margin-bottom: 1rem;
    }

        .panel.panel-purple {
            border: 2px solid #7f51f4;
            background-color: #dfccff;
            color: #7f51f4;
            text-align: center;
        }
</style>


<div class="container">

    <h3>@ViewBag.error</h3>

    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-2">
                <div class="panel panel-purple">
                    <div> @Html.DisplayFor(modelItem => item.SlotNo)</div>
                    <div> @Html.DisplayFor(modelItem => item.VehicleType)</div>
                    <div><h6> @Html.DisplayFor(modelItem => item.VehicleNumber)</h6></div>

                </div>
            </div>
        }
    </div>

</div>
<input type="button" value="HomePage" class="btn btn-primary btn-lg btn-block" onclick="location.href='@Url.Action("HomePage", "BookingSlots")'" />

ParkingMgmt/Views/BookingSlots/BookSlot.cshtml
@model ParkingSlotDataLib.BookingSlot

@{
    ViewBag.Title = "BookSlot";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Book New Slot</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.VehicleNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.VehicleNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.VehicleNumber, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.VehicleType, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
              <h4>@Html.DropDownList("VehicleType", new SelectList(ViewBag.DropDown), "Select Vehicle Type", null)</h4>
            @Html.ValidationMessageFor(model => model.VehicleType, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Book Slot" class="btn btn-primary btn-lg btn-block" />
        </div>
    </div>
</div>
}

ParkingMgmt/Views/BookingSlots/Delete.cshtml
@model ParkingSlotDataLib.BookingSlot
<h3>Are you sure you want to Unallocated this Slots</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.VehicleNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VehicleNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AllocatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AllocatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AllocatedTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AllocatedTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VehicleType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VehicleType)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="button" value="Back" class="btn btn-primary btn-lg btn-block" onclick="location.href='@Url.Action("UnallocateParkingSlot", "BookingSlots")'" />
        <input type="submit" value="Confirm" class="btn btn-danger btn-lg btn-block" style="background-size:100px" />
    </div>
    }
</div>

ParkingMgmt/Views/BookingSlots/Edit.cshtml
@model ParkingSlotDataLib.BookingSlot

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BookingSlot</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.VehicleNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VehicleNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VehicleNumber, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.VehicleType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VehicleType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VehicleType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

ParkingMgmt/Views/BookingSlots/HomePage.cshtml
<h2>HomePage</h2>


    <input type="button" value="Show Avialable Slots"  class="btn btn-primary btn-lg btn-block" onclick="location.href='@Url.Action("SlotAvaiabilty", "BookingSlots")'" />

    <input type="button" value="All Slots" class="btn btn-primary btn-lg btn-block" onclick="location.href='@Url.Action("AllSlots", "BookingSlots")'" />

    <input type="button" value="Book New Slots" class="btn btn-primary btn-lg btn-block" onclick="location.href='@Url.Action("BookSlot", "BookingSlots")'" />

    <input type="button" value="UnAllocate Parking Slot" class="btn btn-primary btn-lg btn-block" onclick="location.href='@Url.Action("UnallocateParkingSlot", "BookingSlots")'" />

    <input type="button" value="Parking History" class="btn btn-primary btn-lg btn-block" onclick="location.href='@Url.Action("ParkingHistory", "BookingSlots")'" />

ParkingMgmt/Views/BookingSlots/ParkingHistory.cshtml
@model IEnumerable<ParkingSlotDataLib.History>

@{
    ViewBag.Title = "ParkingHistory";
}

<h2>ParkingHistory</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.VehicleNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AllocatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AllocatedTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnAllocatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnAllocatedTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SlotNo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.VehicleNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AllocatedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AllocatedTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UnAllocatedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UnAllocatedTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SlotNo)
            </td>
        </tr>
    }
    

</table>
<input type="button" value="HomePage" class="btn btn-primary btn-lg btn-block" onclick="location.href='@Url.Action("HomePage", "BookingSlots")'" />

ParkingMgmt/Views/BookingSlots/SlotAvaiabilty.cshtml
@model IEnumerable<ParkingSlotDataLib.BookingSlot>
@{

    ViewBag.Title = "SlotAvaiabilty";
}

<style>
    .Wrapper{
        color: red;
    }
</style>
<div>
    <br />
    <br />
    <br />
    @using (Html.BeginForm("availableslots", "BookingSlots", FormMethod.Get))
    {
        <h3>@Html.DropDownList("VehicleType", new SelectList(ViewBag.DropDown), "Select Vehicle Type", null)</h3><div class="Wrapper">@ViewBag.error</div>
        <input type="submit" value="Check Slot Avaiability" class="btn btn-success btn-lg btn-block" />
    }   @*<button onclick="GetSelectedType()">Check Slot Avaiability</button>*@

</div>

ParkingMgmt/Views/BookingSlots/UnallocateParkingSlot.cshtml
@model IEnumerable<ParkingSlotDataLib.BookingSlot>

@{
    ViewBag.Title = "UnallocateParkingSlot";
}

<h2>Select Vehicle To Unallocate</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.VehicleNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AllocatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AllocatedTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VehicleType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SlotNo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.VehicleNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AllocatedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AllocatedTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VehicleType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SlotNo)
        </td>
        <td>
            @Html.ActionLink("Unallocate Vehicle", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

ParkingMgmt/Views/BookingSlots/availableslots.cshtml
@model IEnumerable<ParkingSlotDataLib.BookingSlot>

@{
    ViewBag.Title = "availableslots";
}

<h2>Avialable Slots</h2>

<style>
    body {
        margin: 4rem 0;
    }

    h4 {
        margin-bottom: 2rem;
        margin-top: 3rem;
    }

    .panel {
        height: auto;
        width: auto;
        border-radius: 0.2rem;
        padding: 1rem;
        margin-bottom: 0.2rem;
    }

        .panel.panel-purple {
            border: 1px solid #7f51f4;
            background-color: #dfccff;
            color: #7f51f4;
            text-align: center;
        }
</style>


<div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-2">
                    <div class="panel panel-purple">
                        <h4>
                            <b>
                                @Html.DisplayFor(modelItem => item.SlotNo)
                            </b>
                        </h4>
                        @Html.DisplayFor(modelItem => item.VehicleType)
                    </div>
                </div>
            }
        </div>
</div>

ParkingMgmt/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ParkingMgmt/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ParkingMgmt/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ParkingMgmt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Parking Slot Managment System", "HomePage", "BookingSlots", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "HomePage", "BookingSlots")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>